### ISSUE TITLE
Move from rustyline to crossterm

### ISSUE THREAD

**Issue by n-shift** [neo-sh/neosh#19]
We need this one to use [tui](https://lib.rs/tui). If we have both rustyline and crossterm they will steal input from each other as crossterm is registering it's input handler.

## Tasks
- [x] rustyline -> crossterm in Cargo.toml
- [ ] Set up history saver
- [ ] Rewrite built-in commands
- [ ] Rewrite input handler loop
